spring:
    datasource:
        url: jdbc:h2:mem:posts-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        username: sa
        password:
        driver-class-name: org.h2.Driver
    sql:
        init:
            mode: always
    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

server:
    servlet:
        context-path: /myAppMovedToBoot
    port: 5052
    error:
        include-stacktrace: always